services:

  db:
    image: postgres
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    environment:
      - PORT=${API_PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
